# Generated by Django 5.2.5 on 2026-01-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0002_alter_college_id_alter_college_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='university',
            field=models.CharField(blank=True, help_text='Name of affiliated university', max_length=255, null=True),
        ),
    ]
