# Generated by Django 6.0.1 on 2026-01-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0003_college_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (used if image is not uploaded)', null=True),
        ),
    ]
