# Generated by Django 5.2.5 on 2026-01-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0004_college_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='college',
            name='university',
            field=models.CharField(blank=True, help_text='Name of affiliated university', max_length=500, null=True),
        ),
    ]
