# Generated by Django 5.2.5 on 2026-01-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0005_alter_college_name_alter_college_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (used if image is not uploaded)', max_length=500, null=True),
        ),
    ]
